accounts/urls.py
from django.urls import path, re_path
from . import views
from . import models

app_name = 'accounts'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('updateuser/', views.updateuser, name='updateuser'),
    #re_path(r'^(?P<slug>[\w-]+)/$', views.Profile, name='profile'),
]

ninth_project/urls.py
from django.contrib import admin
from django.urls import path , re_path
from django.urls import include
from ninth_app import views
#Can see profile
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',views.index,name='index'),
    path('', include('ninth_app.urls')),# namespace="ninth_app")),
    path('admin/', admin.site.urls),
    path('account/', include("accounts.urls", namespace="accounts")),
    # path('retorno/pagseguro/', include('pagseguro.urls')),
    # TODO a url de retorno será /retorno/pagseguro/
    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base/Lorem1.html
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

templates/base/about.html
<!DOCTYPE html>
{% extends "base/base.html" %}
    {% block body_block %}
        <h1>ABOUT Page.html</h1>
    {% endblock %}

templates/base/base.html
<!DOCTYPE html>
{% load static %}
{% comment %}
 my comments
{% endcomment %}
<html lang="pt-br" dir="ltr">
            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <meta http-equiv="X-UA-Compatible" content="ie=edge">
              <title>Super Modelo Facil</title>
              <!-- Latest compiled and minified CSS -->
              <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

              <!-- Alternative to fontawesome Glyphicons -->
              <!-- I don't use this moment -->
              {# Custom CSS#}
              <link rel="stylesheet" href="{% static 'css/base.css' %}">
              <link rel="stylesheet" href="{% static 'css/index.css' %}">
              {% block head_block %}
                <!-- Anythink outside of this will be inherited if you extend! -->
              {% endblock %}

              <!-- {# Fonts#}
              <link href="https://fonts.googleapis.com/css?family=Montserrat|Russo+One" rel="stylesheet"> -->
            </head>


          <body>
              {% include "base/navbar.html" %}
                {% block body_block %}
                  <!-- Anythink outside of this will be inherited if you extend! -->
                {% endblock %}
              {% include "base/footer.html" %}
            
                

            </body>
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
      
      <script src="{% static 'js/typed.min.js' %}"></script>
      <script src="{% static 'js/typing.js' %}"></script>
      <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script> -->
</html>

templates/base/cardgroup.html
{% load static %}
<div class="card-group">
                          <div class="card">
                            <img src="{% static 'images/avengers4.jpg' %}" class="card-img-top" alt="...">
                            <div class="card-body">
                              <h5 class="card-title">Card title</h5>
                              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                            </div>
                            <div class="card-footer">
                              <small class="text-muted">Last updated 3 mins ago</small>
                            </div>
                          </div>
                          <div class="card">
                            <img src="{% static 'images/avengersEnd.jpg' %}" class="card-img-top" alt="...">
                            <div class="card-body">
                              <h5 class="card-title">Card title</h5>
                              <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
                            </div>
                            <div class="card-footer">
                              <small class="text-muted">Last updated 3 mins ago</small>
                            </div>
                          </div>
                          <div class="card">
                            <img src="{% static 'images/aven4.jpg' %}" class="card-img-top" alt="...">
                            <div class="card-body">
                              <h5 class="card-title">Card title</h5>
                              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
                            </div>
                            <div class="card-footer">
                              <small class="text-muted">Last updated 3 mins ago</small>
                            </div>
                          </div>
                </div>

templates/base/footer.html
<!DOCTYPE html>

<footer>
                  <div class="container">
                      <div class="copyright">
                        <p>Copyright {% now "Y" %} - Company</p>
                      </div>
                      <div class="social">
                        <a href="https://rodrigonegao.github.io/" id="support">Contato</a>
                        <a href="#" id="face">Facebook</a>
                        <a href="#" id="insta">Instagram</a>
                        <a href="#" id="linked">LinkedIn</a>
                      </div>
                  </div>
</footer>

templates/base/index.html
<!DOCTYPE html>
{% extends "base/base.html" %}
{% load static %}

    {% block body_block %}
        <!-- Masthead -->
        <header class="masthead text-white text-center">
            <div class="overlay"></div>
            <div class="container">
              <div class="row">
                <div class="col-xl-9 mx-auto">
                  <h1 class="mb-5"><span id="typing"></span>&nbsp;</h1>
                </div>
                <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
                  {% comment %} <form method="POST">
                    <div class="form-row">
                      <div class="col-12 col-md-9 mb-2 mb-md-0">
                        <input type="text" class="form-control form-control-lg" placeholder="Pesquise">
                      </div>
                      <div class="col-12 col-md-3">
                        <button type="submit" class="btn btn-block btn-lg btn-primary">Search</button>
                      </div>
                    </div>
                  </form> {% endcomment %}
                </div>
              </div>
            </div>
          </header>
        {% comment %} <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
                  <div class="carousel-inner">
                    <div class="carousel-item active">
                      <img src="{% static 'images/avengers4.jpg' %}" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                      <img src="{% static 'images/avengersend.jpg' %}" class="d-block w-100" alt="...">
                    </div>
                  </div>
                  <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                  </a>
                  <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                  </a>
        </div>{% endcomment %}
            <br>
                    {% comment %} {% include "base/listview1.html" %}
                     {% endcomment %}
                        <div class="title2"> Modelos  </div>
                        {% include "base/listview2.html" %}
                          
                          <br>
                          <br>
                        {% include "base/listview3.html" %}
                          <br>
                          <br>
                        <div class="title2"> Cards  </div>
                        {% include "base/cardgroup.html" %}
                          <br>
                          <br>
                        <div class="title2"> Lorem  </div>
                        {% include "base/Lorem1.html" %}
        
    {% endblock %}

templates/base/listview1.html
<!DOCTYPE html>
{% comment %} Tests  {% endcomment %}
<h2>Urls</h2>
                      <ul>
                          {% for url_name in urlpatterns %}
                        <li><a href="{% url url_name.name %}"> {{ urlpatterns.name }}</a> </li>
                        {% endfor %}
                      </ul>

<h2>Urls2</h2>
{% comment %} <a href="{% url 'news-year-archive' 2012 %}">2012 Archive</a> {% endcomment %}
{# Or with the year in a template context variable: #}
<ul>
{% for yearvar in year_list %}
<li><a href="{% url 'news-year-archive' yearvar %}">{{ yearvar }} Archive</a></li>
{% endfor %}
</ul>

templates/base/listview2.html
{% load static %}

<div class="row">
                                  <div class="col-sm-6"><ul class="list-unstyled">
                                    <li class="media">
                                      <a href="{% url 'resumetemp' %}"><img src="{% static 'images/icon_64x64.png' %}" class="mr-3 rounded-left" alt="..."></a>
                                      <div class="media-body" >
                                        <a href="{% url 'resumetemp' %}"><h5 class="mt-0 mb-1" >Curriculo</h5></a>
                                        Crie seu Curriculo Online em PDF com QR Code. 
                                      </div>
                                    </li>
                                    <li class="media my-4">
                                      <a href="{% url 'recibosimplesdados' %}"><img src="{% static 'images/icon_64x64.png' %}" class="mr-3 rounded-left" alt="..."></a>
                                      <div class="media-body">
                                        <a href="{% url 'recibosimplesdados' %}"><h5 class="mt-0 mb-1">Recibo Simples</h5></a>
                                        Faça Um Recibo de modo Simples e Rápido 
                                      </div>
                                    </li>
                                    <li class="media">
                                      <a href="{% url 'contratosimplesdados' %}"><img src="{% static 'images/icon_64x64.png' %}" class="mr-3 rounded-left" alt="..."></a>
                                      <div class="media-body">
                                        <a href="{% url 'contratosimplesdados' %}"><h5 class="mt-0 mb-1">Contrato de Aluguel</h5></a>
                                        Um Contrato Rapido e Seguro para Aluguel
                                      </div>
                                    </li>
                                  </ul></div>
                                  <div class="col-sm-6"><ul class="list-unstyled">
                                    <li class="media">
                                      <a href="{% url 'procsimplesdados' %}"><img src="{% static 'images/icon_64x64.png' %}" class="mr-3 rounded-left" alt="..."></a>
                                      <div class="media-body">
                                        <a href="{% url 'procsimplesdados' %}"><h5 class="mt-0 mb-1">Procuração</h5></a>
                                        Procuração Simples e Rápida.
                                      </div>
                                    </li>
                                    <li class="media my-4">
                                      <a href="{% url 'automenordados' %}"><img src="{% static 'images/icon_64x64.png' %}" class="mr-3 rounded-left" alt="..."></a>
                                      <div class="media-body">
                                        <a href="{% url 'automenordados' %}"><h5 class="mt-0 mb-1">Autorização de Menor</h5></a>
                                        Autorização Aceito em quase todos os lugares.
                                      </div>
                                    </li>
                                    {% comment %} <li class="media">
                                      <a href="{% url 'recibosimplesdados' %}"><img src="{% static 'images/icon_64x64.png' %}" class="mr-3 rounded-left" alt="..."></a>
                                      <div class="media-body">
                                        <a href="{% url 'recibosimplesdados' %}"><h5 class="mt-0 mb-1">List-based media object</h5></a>
                                        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                                      </div>
                                    </li> {% endcomment %}
                                  </ul></div>
                          </div>

templates/base/listview3.html
{% load static %}
<ul class="list-unstyled">
                              <li class="media">
                                <img src="{% static 'images/icon_64x64.png' %}" class="mr-3 rounded-left" alt="...">
                                <div class="media-body">
                                  <h5 class="mt-0 mb-1">List-based media object</h5>
                                  Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                                </div>
                              </li>
                              <li class="media my-4">
                                <img src="{% static 'images/icon_64x64.png' %}" class="mr-3 rounded-left" alt="...">
                                <div class="media-body">
                                  <h5 class="mt-0 mb-1">List-based media object</h5>
                                  Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                                </div>
                              </li>
                              <li class="media">
                                <img src="{% static 'images/icon_64x64.png' %}" class="mr-3 rounded-left" alt="...">
                                <div class="media-body">
                                  <h5 class="mt-0 mb-1">List-based media object</h5>
                                  Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                                </div>
                              </li>
                            </ul>

templates/base/navbar.html
<!DOCTYPE html>
    <nav class="navbar sticky-top navbar-expand-lg navbar-dark shadow " style="background-color: black;">

        <a class="navbar-brand" href="{% url 'index' %}">Company</a>
        {% comment %}
          Brand and toggle get grouped for better mobile display
          This is the actual code that creates the "hamburger icon"
          The data-target grabs ids to put into the icon
        {% endcomment %}

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-controls="bs-example-navbar-collapse-1" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        {% comment %}
          Anything inside of collapse navbar-collapse goes into the "hamburger"
        {% endcomment %}


        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <div class="navbar-nav">
            {% comment %}
               the span class "sr-only" tells screen readers that Home is the active link, for accessibility
            {% endcomment %}

            <a class="nav-item nav-link {% if request.resolver_match.url_name == 'index' %}active{% endif %}" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link {% if request.resolver_match.url_name == 'resumetemp' %}active{% endif %}" href="{% url 'resumetemp' %}">Crie seu Curriculo</a>
            {% comment %} <a class="nav-item nav-link" href="{% url 'recibo' %}">Recibo PDF</a> {% endcomment %}
          </div>

                    <div class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle active" href="#" id="navbar-dropdown-menu" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dropdown
                      </a>
                      <div class="dropdown-menu" aria-labelledby="navbar-dropdown-menu">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="http://www.google.com">Go to Google</a>
                        <a class="dropdown-item" href="#">Something else here</a>

                        <!-- Use this to separate a new link: -->
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Separated link</a>
                      </div>
                    </div>
          <div class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                    {% comment %}
                         <!-- LOGIN -->
                    {% endcomment %}
                    <div class="btn-group">
                        <button type="button" class="btn btn-secondary">Olá {{ user.username }}</button>
                        <button type="button" class="btn btn-secondary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="sr-only">Toggle Dropdown</span>
                        </button>
                        <div class="dropdown-menu">
                          <a class="dropdown-item" href="{% url 'accounts:updateuser' %}">Perfil</a>
                          <div class="dropdown-divider"></div>
                          <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
                        </div>
                    </div>
                    {% comment %}
                        <a class="nav-item nav-link" href="#" class="btn btn-simple activate">Olá {{ user.username }}</a>
                          <a class="nav-item nav-link" href="{% url 'accounts:logout' %}" class="btn btn-simple">Logout</a>
                    {% endcomment %}
            {% else %}
              <a class="nav-item nav-link" href="{% url 'accounts:login' %}" class="btn btn-simple">Login</a>
              <a class="nav-item nav-link" href="{% url 'accounts:signup' %}" class="btn btn-simple">Cadastre-se</a>
            {% endif %}
            {% comment %}
                 <!-- <a class="nav-item nav-link" href="#">On Right</a> -->
            {% endcomment %}

          </div>

        </div>
    </nav>